---
- hosts: localhost
  tasks:
    - name: execute command
      shell: touch sample.txt
      
    - name: command
      shell: uname -a
      register: comd
      
    - debug: var=comd.stdout_lines
